call to action btn and text
cecile-dzy-ncl/BM pull request #10
Opened 2021-02-07 22:41 UTC by nicocapalbo

2021-02-08 20:49 UTC, cecile-dzy-ncl requested changes

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/homepage.html
> +        <p class='cta-text'>Alors, prêt à vous lancer dans cette aventure solidaire ?</p>
this should be a h3

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/homepage.html
> +        <p class='btn-primary'>Créer ma page de collecte</p>
there is a btn class already existing in the global css files ... 
i always use btn-bm that i adapt to my needs + the bg-nameoftheprimarycolor for the background color

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/css/style.css
> +@import "../css/cta.css";
buttons.css

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/css/cta.css
> +.cta-text {
this should be a h3 so put it in the font.css file

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/css/cta.css
> +.cta-text {
and without the class, just style the h3 tag

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/css/cta.css
> +.btn-primary {
name of the btn class should be btn-bm, check what's already existing in the global css file and adapt to your need

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/css/cta.css
> +  height: 80px;
never put height and width (but do put some padding)

2021-02-08 20:49 UTC, cecile-dzy-ncl commented on pfdp/css/cta.css
> +  margin-left: 33%;
😱 
if you want to center a block or inlin-block element, you do it the following way :
`margin: 0 auto;`
here the margin is already in button global css

2021-02-09 16:17 UTC, cecile-dzy-ncl requested changes

2021-02-09 16:17 UTC, cecile-dzy-ncl commented on pfdp/css/button.css
> +  margin: 30px 25%;
nooooooooooooo 
tsss
`margin: 0 auto`

2021-02-09 16:17 UTC, cecile-dzy-ncl commented on pfdp/css/button.css
> +    margin: 10px 0%;
same here

2021-02-09 16:43 UTC, nicocapalbo commented on pfdp/css/button.css
> +    margin: 10px 0%;
removed

2021-02-09 16:44 UTC, nicocapalbo commented on pfdp/css/button.css
> +  margin: 30px 25%;
removed margin, inserted **width: fit-content;**

2021-02-09 18:26 UTC, cecile-dzy-ncl requested changes

2021-02-09 18:26 UTC, cecile-dzy-ncl commented on pfdp/css/button.css
> +    padding: 15px;
why the change of padding in responsive ?

2021-02-10 11:13 UTC, merged